### ISSUE TITLE
Torch problem + model not found

### ISSUE THREAD

**Issue by Adzido** [Ynn/sd-webui-faceswap#7]
Hello, today I wanted to install this plugin cuz this looks so good, but...

I followed this:
https://github.com/s0md3v/roop/wiki/1.-Installation

At the point: "cd roop && pip install -r requirements.txt" I had error at end of install. 

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.16 requires torch==1.13.1, but you have torch 2.0.1+cu118 which is incompatible.

I found in internet some info about this and they said I can just ignore this, thats right? Can I ignore it? If not, how to fix it? And that's why I have a different version (probably a newer one because it's 2 there, and it needs 1)? It is possible that some other plug-in in SD required it and installed its newer version?

Next problem is I have model in stable-diffusion-webui\extensions\sd-webui-faceswap-main\models named inswapper_128.onnx but my SD gave me info:

> 2023-06-11 15:31:16,442 - FaceSwap - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/Ynn/sd-webui-faceswap/

And yeah, does not show this model in the A111. I cant use FaceSwap.

How to fix it? Thanks!
I specially created an account on GitHub to get help here, I hope it will work.

**Comment by Ynn** [comment]
Oh you don't need to install roop, the extension should install the necessary stuff. You only need a model, same as for roop and place it in models/FaceSwap. Once it done restart automatic 1111

**Comment by Adzido** [comment]
From the description it seems that it should install because you used a link to roop.
I reinstalled plug-in and everything works. That's really great!

Is it possible to faceswap anime characters somehow?
Is there perhaps an option in the plans such that it would swap the face along with the hair?

**Comment by Ynn** [comment]
I didn't develop the underlying technology (insightface), and their tool is only for exchanging faces, not hair (which is good in my view). You may use the controlnet reference to improve similarity.

As for animated characters, this can sometimes work. It depends on the realism of the original drawing.
